name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pyspark
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install pypandoc
          pip install pyspark
      - name: Run python tests
        run: |
          cd python
          python3 -m unittest discover